### ISSUE TITLE
When I trying to fetch ad campaign with your example i am getting error.

### ISSUE THREAD

**Issue by cayirburak** [linkedin-developers/linkedin-api-python-client#17]
When i try to fetch ad campaign based your [example](https://github.com/linkedin-developers/linkedin-api-python-client/blob/main/examples/batch_get_campaign_groups_query_tunneling.py) i am getting error something like that.

`Traceback (most recent call last):
  File "/home/burak/projects_folder/b2m_mongo_api/app/core/linkedin_marketing_api.py", line 5, in <module>
    from linkedin_api.clients.restli.client import RestliClient
  File "/home/burak/.cache/pypoetry/virtualenvs/b2m-mongo-api-8MuF3G3a-py3.8/lib/python3.8/site-packages/linkedin_api/clients/restli/client.py", line 4, in <module>
    from linkedin_api.clients.common.response import BaseResponse
  File "/home/burak/.cache/pypoetry/virtualenvs/b2m-mongo-api-8MuF3G3a-py3.8/lib/python3.8/site-packages/linkedin_api/clients/common/response.py", line 4, in <module>
    class BaseResponse:
  File "/home/burak/.cache/pypoetry/virtualenvs/b2m-mongo-api-8MuF3G3a-py3.8/lib/python3.8/site-packages/linkedin_api/clients/common/response.py", line 5, in BaseResponse
    def __init__(self, status_code: int, headers: CaseInsensitiveDict[str], url: str, response: Response):
TypeError: 'ABCMeta' object is not subscriptable`

python : 3.8.10
requests : 2.28.2 

Thanks
Burak

**Comment by shimizust** [comment]
@cayirburak Thanks for raising this issue--this error exists for python 3.7/3.8 and was just fixed in this recent PR (#16).

I will release a new version of the library today with the fix and update this ticket.

**Comment by shimizust** [comment]
Closing issue. Feel free to re-open if not working
